### ISSUE TITLE
Greenfield CLI in Linux System

### ISSUE THREAD

**Issue by sudharsansubash2002** [bnb-chain/greenfield-cmd#107]
When attempting to build on Linux servers (tried on different versions, including Amazon Linux and Ubuntu), I encounter an error when executing the "make build" command. 

I've used the **Greenfield CLI version 1.0.2** (latest), and I've tried with two different Go versions: 

- go1.25.5 and 
- go1.20.0.

 Is there anything I might be missing?

`ubuntu@ip-172-31-32-35:~/greenfield-cmd-1.0.2$ make build
go build -o ./build/gnfd-cmd cmd/*.go

 #internal/abi

../go/src/internal/abi/funcpc.go:22:6: FuncPCABI0 redeclared in this block
        ../go/src/internal/abi/abi.go:117:6: other declaration of FuncPCABI0
../go/src/internal/abi/funcpc.go:31:6: FuncPCABIInternal redeclared in this block
        ../go/src/internal/abi/abi.go:126:6: other declaration of FuncPCABIInternal
make: *** [Makefile:6: build] Error 1`

**Comment by deepcrazy** [comment]
Hi there, Can you confirm you followed the exact below steps:
- https://github.com/bnb-chain/greenfield-cmd?tab=readme-ov-file#installation ?

Also, Can you share the below details:
- more logs after running `make build` command with go1.20.* version.
- ubuntu version

P.S: I tried on my end with go1.20.3 version and greenfield CLI version v1.0.2 and it did worked fine. You can probably try to use go1.20.3 version once too and see if it works.
