### ISSUE TITLE
create bucket failed

### ISSUE THREAD

**Issue by flyhxg** [bnb-chain/greenfield-cmd#23]
hello,Hello, why did this error occur? The parameter is configured with a private key,
![image](https://user-images.githubusercontent.com/11693167/232693743-db3eb9c2-8a3d-4913-9a37-eadd7952f0c0.png)
![1681800457904](https://user-images.githubusercontent.com/11693167/232694156-c6c2b550-3c57-4372-b692-185b7962ea66.png)

**Comment by kris-ss** [comment]
Hello, the error means that the private key entered is invalid. How did you generate it?


You can try this one for your testing? 61d74bb4b0e48e70ea6c955786e69c2c070c8c71fd8e8401f956bc96baa3e81e

endpoint = "gnfd-testnet-sp-1.nodereal.io"
grpcAddr = "gnfd-testnet-fullnode-cosmos-us.bnbchain.org:9090"
chainId = "greenfield_5600-1"
privateKey = "61d74bb4b0e48e70ea6c955786e69c2c070c8c71fd8e8401f956bc96baa3e81e"

**Comment by kris-ss** [comment]
Hello @flyhxg your command is missing a value for the --primarySP parameter.

Example: ./gnfd-cmd -c config.toml mb --primarySP **0x02Ad74D9B2349c2f0B1e9598aB018B3414dDe87A**  --visibility=public-read gnfd://bucket-testxx

To get the address of an SP, ./gnfd-cmd -c config.toml ls-sp

![Screenshot 2023-04-18 at 3 15 16 PM](https://user-images.githubusercontent.com/113088090/232760751-f9281fbf-9725-45de-95ba-abe279693b41.png)

**Comment by flyhxg** [comment]
Thank you. The creation of the bucket was successful, but the upload file indicates that the bucket does not exist, and even with the command ls, the bucket does not exist
![1681871065147](https://user-images.githubusercontent.com/11693167/232950329-6d0c9621-c935-49fb-9d27-cbff54e7cbb3.png)

**Comment by flywukong** [comment]
hello @flyhxg,   your bucket seems to be deleted.  You can run head-bucket cmd to make sure the bucket exist.               
 <img width="1653" alt="image" src="https://user-images.githubusercontent.com/19421226/232962949-8926e7d2-a34b-49aa-a875-977463f583b2.png"> ..

**Comment by flyhxg** [comment]
> head-bucket

![1681877983202](https://user-images.githubusercontent.com/11693167/232966176-0fa66ebe-f9ef-4957-afd8-f6bd91a7f5c3.png)
Although the creation was successful, the bucket output does not exist?

**Comment by flyhxg** [comment]
Okay, thank you. It seems like it's my chain_ The ID is incorrect. It's ready now. Thank you very much
