### ISSUE TITLE
putting multiple objects

### ISSUE THREAD

**Issue by cemleme** [bnb-chain/greenfield-cmd#73]
current command accepts only 1 file input while dcellar.io allows multiple file upload in single transaction.

usage: gnfd-cmd object put file.txt gnfd://gnfd-bucket/gnfd-object

is it possible to upload multiple files using gnfd-cmd?

**Comment by deepcrazy** [comment]
Hi there, As per this docs: https://docs.bnbchain.org/greenfield-docs/docs/guide/getting-started/greenfield-command#uploaddownload-files, you can can specify 1 file as input. However, let me check internally if there is a way for multiple files upload using gnfd-cmd.

**Comment by flywukong** [comment]
@cemleme  gnfd-cmd has supported uploading multiple files or local folder in the latest version. You can find the usage in README.

**Comment by flywukong** [comment]
1
