### ISSUE TITLE
Why does 'sealing' keep repeating when I put an object?

### ISSUE THREAD

**Issue by jlguochn** [bnb-chain/greenfield-cmd#98]
uploading progress: 100.00% [ 4B / 4B ], rate: 0.11 Byte/s
sealing...
sealing...
sealing...
sealing...
sealing...
sealing...
sealing...
sealing...

**Comment by jlguochn** [comment]
# put object
./gnfd-cmd -c ./config.toml --home ./ object put --contentType "application/octet-stream" ./random_file gnfd://${BUCKET_NAME}/random_file

**Comment by jlguochn** [comment]
./gnfd-cmd -c ./config.toml --home ./ object put --contentType "application/octet-stream" ./random_file gnfd://${BUCKET_NAME}/random_file

**Comment by jlguochn** [comment]
Now it has been uploaded successfully because the time it takes for 'wait for block_syncer to sync up data from chain' is relatively long.

**Comment by flywukong** [comment]
Normally, you don’t need to wait for such a long time. This may be related to the online upgrade . It will keep on printing sealing until it has been sealed . You can set "bypassSeal " flag to bypass the waiting.
